### ISSUE TITLE
Support for big datasets

### ISSUE THREAD

**Issue by tk-king** [edge-ml/edge-ml#38]
The system should support large datasets. For this to work we need to change the time-series storage mechanisms in the backend and maybe also the data processing of the time series in all parts of the system.

**Comment by tk-king** [comment]
Load the UCI-HAR datasets or any other large dataset into the system and see if it works and what the bottlenecks are.

**Comment by tk-king** [comment]
- 18MB dataset (UCI-HAR testing dataset) takes about 2:50 to upload
- During upload chrome reports unresponsive site
- edge-ml has inefficient time series mechanisms
- page for datasets is unusable for large datasets (e.g. labeling takes too long)

**Comment by tk-king** [comment]
Save time series not in MongoDB but as a binary file on the disk. Reference the time series file then from MongoDB. Think about binary data streaming for time series from the backend to the frontend.

**Comment by KtrauM** [comment]
Some low priority things I also observed during the dataset upload can be improved for a better UX:
- [ ] More descriptive error messages when the dataset format is not correct, currently it shows where the error occured but not why.
- [ ] Typo in error message 'colum' instead of 'column
- [ ] Uploaded column names can be listed in the UI and edited to conform the format with adequate feedback
- [ ] Time column can be automatically added by setting a start time and sampling frequency if not present

**Comment by tk-king** [comment]
Use GridFS in MongoDB to store the data as binary files (on a per time series basis)

**Comment by tk-king** [comment]
- [ ] Update CSV-upload-page to support large datasets. Make it run in the backend.
- [ ] Optimize performance of dataset page in the frontend, especially for labelling
